window.BIBTEX_RAW = String.raw`

@inproceedings{oguz_find-2-find_2023,
	location = {Singapore},
	title = {Find-2-Find: Multitask Learning for Anaphora Resolution and Object Localization},
	url = {https://aclanthology.org/2023.emnlp-main.504/},
	doi = {10.18653/v1/2023.emnlp-main.504},
	shorttitle = {Find-2-Find},
	abstract = {In multimodal understanding tasks, visual and linguistic ambiguities can arise. Visual ambiguity can occur when visual objects require a model to ground a referring expression in a video without strong supervision, while linguistic ambiguity can occur from changes in entities in action flows. As an example from the cooking domain, “oil” mixed with “salt” and “pepper” could later be referred to as a “mixture”. Without a clear visual-linguistic alignment, we cannot know which among several objects shown is referred to by the language expression “mixture”, and without resolved antecedents, we cannot pinpoint what the mixture is. We define this chicken-and-egg problem as Visual-linguistic Ambiguity. In this paper, we present Find2Find, a joint anaphora resolution and object localization dataset targeting the problem of visual-linguistic ambiguity, consisting of 500 anaphora-annotated recipes with corresponding videos. We present experimental results of a novel end-to-end joint multitask learning framework for Find2Find that fuses visual and textual information and shows improvements both for anaphora resolution and object localization with one joint model in multitask learning, as compared to a strong single-task baseline.},
	eventtitle = {{EMNLP} 2023},
	pages = {8099--8110},
	booktitle = {Proceedings of the 2023 Conference on Empirical Methods in Natural Language Processing},
	publisher = {Association for Computational Linguistics},
	author = {Oguz, Cennet and Denis, Pascal and Vincent, Emmanuel and Ostermann, Simon and van Genabith, Josef},
	urldate = {2025-05-22},
	date = {2023-12},
	note = {f2f.jpg},
	keywords = {{EMNLP}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/PXGQQHKK/Oguz et al. - 2023 - Find-2-Find Multitask Learning for Anaphora Resol.pdf:application/pdf},
}

@inproceedings{baeumel_investigating_2023,
	location = {Singapore},
	title = {Investigating the Encoding of Words in {BERT}`s Neurons Using Feature Textualization},
	url = {https://aclanthology.org/2023.blackboxnlp-1.20/},
	doi = {10.18653/v1/2023.blackboxnlp-1.20},
	abstract = {Pretrained language models ({PLMs}) form the basis of most state-of-the-art {NLP} technologies. Nevertheless, they are essentially black boxes: Humans do not have a clear understanding of what knowledge is encoded in different parts of the models, especially in individual neurons. A contrast is in computer vision, where feature visualization provides a decompositional interpretability technique for neurons of vision models. Activation maximization is used to synthesize inherently interpretable visual representations of the information encoded in individual neurons. Our work is inspired by this but presents a cautionary tale on the interpretability of single neurons, based on the first large-scale attempt to adapt activation maximization to {NLP}, and, more specifically, large {PLMs}. We propose feature textualization, a technique to produce dense representations of neurons in the {PLM} word embedding space. We apply feature textualization to the {BERT} model to investigate whether the knowledge encoded in individual neurons can be interpreted and symbolized. We find that the produced representations can provide insights about the knowledge encoded in individual neurons, but that individual neurons do not represent clear-cut symbolic units of language such as words. Additionally, we use feature textualization to investigate how many neurons are needed to encode words in {BERT}.},
	pages = {261--270},
	booktitle = {Proceedings of the 6th {BlackboxNLP} Workshop: Analyzing and Interpreting Neural Networks for {NLP}},
	publisher = {Association for Computational Linguistics},
	author = {Baeumel, Tanja and Vijayakumar, Soniya and van Genabith, Josef and Neumann, Guenter and Ostermann, Simon},
	urldate = {2025-05-22},
	date = {2023-12},
	note = {bert\_neurons.jpg},
	keywords = {{BlackBox}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/QLC6YLID/Baeumel et al. - 2023 - Investigating the Encoding of Words in BERT`s Neur.pdf:application/pdf},
}

@inproceedings{rehm_common_2024,
	location = {Torino, Italia},
	title = {Common European Language Data Space},
	url = {https://aclanthology.org/2024.lrec-main.317/},
	abstract = {The Common European Language Data Space ({LDS}) is an integral part of the {EU} data strategy, which aims at developing a single market for data. Its decentralised technical infrastructure and governance scheme are currently being developed by the {LDS} project, which also has dedicated tasks for proof-of-concept prototypes, handling legal aspects, raising awareness and promoting the {LDS} through events and social media channels. The {LDS} is part of a broader vision for establishing all necessary components to develop European large language models.},
	eventtitle = {{LREC}-{COLING} 2024},
	pages = {3579--3586},
	booktitle = {Proceedings of the 2024 Joint International Conference on Computational Linguistics, Language Resources and Evaluation ({LREC}-{COLING} 2024)},
	publisher = {{ELRA} and {ICCL}},
	author = {Rehm, Georg and Piperidis, Stelios and Choukri, Khalid and Vasiļjevs, Andrejs and Marheinecke, Katrin and Arranz, Victoria and Bērziņš, Aivars and Deligiannis, Miltos and Galanis, Dimitris and Giagkou, Maria and Gkirtzou, Katerina and Gkoumas, Dimitris and Grützner-Zahn, Annika and Kolovou, Athanasia and Labropoulou, Penny and Lagzdiņš, Andis and Leitner, Elena and Mapelli, Valérie and Mazo, Hélène and Ostermann, Simon and Racioppa, Stefania and Rigault, Mickaël and Voukoutis, Leon},
	urldate = {2025-05-22},
	date = {2024-05},
	note = {lds.jpg},
	keywords = {Coling},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/TZITTVGA/Rehm et al. - 2024 - Common European Language Data Space.pdf:application/pdf},
}

@inproceedings{srinivasagan_hybridbert_2024,
	location = {Mexico City, Mexico},
	title = {{HybridBERT} - Making {BERT} Pretraining More Efficient Through Hybrid Mixture of Attention Mechanisms},
	url = {https://aclanthology.org/2024.naacl-srw.30/},
	doi = {10.18653/v1/2024.naacl-srw.30},
	abstract = {Pretrained transformer-based language models have produced state-of-the-art performance in most natural language understanding tasks. These models undergo two stages of training: pretraining on a huge corpus of data and fine-tuning on a specific downstream task. The pretraining phase is extremely compute-intensive and requires several high-performance computing devices like {GPUs} and several days or even months of training, but it is crucial for the model to capture global knowledge and also has a significant impact on the fine-tuning task. This is a major roadblock for researchers without access to sophisticated computing resources. To overcome this challenge, we propose two novel hybrid architectures called {HybridBERT} ({HBERT}), which combine self-attention and additive attention mechanisms together with sub-layer normalization. We introduce a computing budget to the pretraining phase, limiting the training time and usage to a single {GPU}. We show that {HBERT} attains twice the pretraining accuracy of a vanilla-{BERT} baseline. We also evaluate our proposed models on two downstream tasks, where we outperform {BERT}-base while accelerating inference. Moreover, we study the effect of weight initialization with a limited pretraining budget. The code and models are publicly available at: www.github.com/gokulsg/{HBERT}/.},
	pages = {285--291},
	booktitle = {Proceedings of the 2024 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies (Volume 4: Student Research Workshop)},
	publisher = {Association for Computational Linguistics. 🏆 Runner Up Best Paper Award},
	author = {Srinivasagan, Gokul and Ostermann, Simon},
	urldate = {2025-05-22},
	date = {2024-06},
	note = {hybridbert.jpg},
	keywords = {{NAACL}-{SRW}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/PSQT6Y2U/Srinivasagan und Ostermann - 2024 - HybridBERT - Making BERT Pretraining More Efficien.pdf:application/pdf},
}

@inproceedings{wang_coxql_2024,
	location = {Miami, Florida, {USA}},
	title = {{CoXQL}: A Dataset for Parsing Explanation Requests in Conversational {XAI} Systems},
	url = {https://aclanthology.org/2024.findings-emnlp.76/},
	doi = {10.18653/v1/2024.findings-emnlp.76},
	shorttitle = {{CoXQL}},
	abstract = {Conversational explainable artificial intelligence ({ConvXAI}) systems based on large language models ({LLMs}) have garnered significant interest from the research community in natural language processing ({NLP}) and human-computer interaction ({HCI}). Such systems can provide answers to user questions about explanations in dialogues, have the potential to enhance users' comprehension and offer more information about the decision-making and generation processes of {LLMs}. Currently available {ConvXAI} systems are based on intent recognition rather than free chat, as this has been found to be more precise and reliable in identifying users' intentions. However, the recognition of intents still presents a challenge in the case of {ConvXAI}, since little training data exist and the domain is highly specific, as there is a broad range of {XAI} methods to map requests onto. In order to bridge this gap, we present {CoXQL}, the first dataset in the {NLP} domain for user intent recognition in {ConvXAI}, covering 31 intents, seven of which require filling multiple slots. Subsequently, we enhance an existing parsing approach by incorporating template validations, and conduct an evaluation of several {LLMs} on {CoXQL} using different parsing strategies. We conclude that the improved parsing approach ({MP}+) surpasses the performance of previous approaches. We also discover that intents with multiple slots remain highly challenging for {LLMs}.},
	eventtitle = {Findings 2024},
	pages = {1410--1422},
	booktitle = {Findings of the Association for Computational Linguistics: {EMNLP} 2024},
	publisher = {Association for Computational Linguistics},
	author = {Wang, Qianli and Anikina, Tatiana and Feldhus, Nils and Ostermann, Simon and Möller, Sebastian},
	urldate = {2025-05-22},
	date = {2024-11},
	note = {coxql.jpg},
	keywords = {{EMNLP}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/2UNURE7Z/Wang et al. - 2024 - CoXQL A Dataset for Parsing Explanation Requests .pdf:application/pdf},
}

@inproceedings{gurgurov_adapting_2024,
	location = {Bangkok, Thailand},
	title = {Adapting Multilingual {LLMs} to Low-Resource Languages with Knowledge Graphs via Adapters},
	url = {https://aclanthology.org/2024.kallm-1.7/},
	doi = {10.18653/v1/2024.kallm-1.7},
	abstract = {This paper explores the integration of graph knowledge from linguistic ontologies into multilingual Large Language Models ({LLMs}) using adapters to improve performance for low-resource languages ({LRLs}) in sentiment analysis ({SA}) and named entity recognition ({NER}). Building upon successful parameter-efficient fine-tuning techniques, such as K-{ADAPTER} and {MAD}-X, we propose a similar approach for incorporating knowledge from multilingual graphs, connecting concepts in various languages with each other through linguistic relationships, into multilingual {LLMs} for {LRLs}. Specifically, we focus on eight {LRLs} — Maltese, Bulgarian, Indonesian, Nepali, Javanese, Uyghur, Tibetan, and Sinhala — and employ language-specific adapters fine-tuned on data extracted from the language-specific section of {ConceptNet}, aiming to enable knowledge transfer across the languages covered by the knowledge graph. We compare various fine-tuning objectives, including standard Masked Language Modeling ({MLM}), {MLM} with full-word masking, and {MLM} with targeted masking, to analyze their effectiveness in learning and integrating the extracted graph data. Through empirical evaluation on language-specific tasks, we assess how structured graph knowledge affects the performance of multilingual {LLMs} for {LRLs} in {SA} and {NER}, providing insights into the potential benefits of adapting language models for low-resource scenarios.},
	pages = {63--74},
	booktitle = {Proceedings of the 1st Workshop on Knowledge Graphs and Large Language Models ({KaLLM} 2024)},
	publisher = {Association for Computational Linguistics},
	author = {Gurgurov, Daniil and Hartmann, Mareike and Ostermann, Simon},
	urldate = {2025-05-22},
	date = {2024-08},
	keywords = {{KaLLM}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/VIZY4KBI/Gurgurov et al. - 2024 - Adapting Multilingual LLMs to Low-Resource Languag.pdf:application/pdf},
}

@inproceedings{vykopal_soft_2025,
	location = {Albuquerque, New Mexico},
	title = {Soft Language Prompts for Language Transfer},
	isbn = {9798891761896},
	url = {https://aclanthology.org/2025.naacl-long.517/},
	abstract = {Cross-lingual knowledge transfer, especially between high- and low-resource languages, remains challenging in natural language processing ({NLP}). This study offers insights for improving cross-lingual {NLP} applications through the combination of parameter-efficient fine-tuning methods. We systematically explore strategies for enhancing cross-lingual transfer through the incorporation of language-specific and task-specific adapters and soft prompts. We present a detailed investigation of various combinations of these methods, exploring their efficiency across 16 languages, focusing on 10 mid- and low-resource languages. We further present to our knowledge the first use of soft prompts for language transfer, a technique we call soft language prompts. Our findings demonstrate that in contrast to claims of previous work, a combination of language and task adapters does not always work best; instead, combining a soft language prompt with a task adapter outperforms most configurations in many cases.},
	eventtitle = {{NAACL}-{HLT} 2025},
	pages = {10294--10313},
	booktitle = {Proceedings of the 2025 Conference of the Nations of the Americas Chapter of the Association for Computational Linguistics: Human Language Technologies (Volume 1: Long Papers)},
	publisher = {Association for Computational Linguistics},
	author = {Vykopal, Ivan and Ostermann, Simon and Simko, Marian},
	urldate = {2025-05-22},
	date = {2025-04},
	note = {softprompts.png},
	keywords = {{NAACL}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/K38LKVSW/Vykopal et al. - 2025 - Soft Language Prompts for Language Transfer.pdf:application/pdf},
}

@inproceedings{wang_cross-refine_2025,
	location = {Abu Dhabi, {UAE}},
	title = {Cross-Refine: Improving Natural Language Explanation Generation by Learning in Tandem},
	url = {https://aclanthology.org/2025.coling-main.77/},
	shorttitle = {Cross-Refine},
	abstract = {Natural language explanations ({NLEs}) are vital for elucidating the reasoning behind large language model ({LLM}) decisions. Many techniques have been developed to generate {NLEs} using {LLMs}. However, like humans, {LLMs} might not always produce optimal {NLEs} on first attempt. Inspired by human learning processes, we introduce Cross-Refine, which employs role modeling by deploying two {LLMs} as generator and critic, respectively. The generator outputs a first {NLE} and then refines this initial explanation using feedback and suggestions provided by the critic. Cross-Refine does not require any supervised training data or additional training. We validate Cross-Refine across three {NLP} tasks using three state-of-the-art open-source {LLMs} through automatic and human evaluation. We select Self-Refine (Madaan et al., 2023) as the baseline, which only utilizes self-feedback to refine the explanations. Our findings from automatic evaluation and a user study indicate that Cross-Refine outperforms Self-Refine. Meanwhile, Cross-Refine can perform effectively with less powerful {LLMs}, whereas Self-Refine only yields strong results with {ChatGPT}. Additionally, we conduct an ablation study to assess the importance of feedback and suggestions. Both of them play an important role in refining explanations. We further evaluate Cross-Refine on a bilingual dataset in English and German.},
	eventtitle = {{COLING} 2025},
	pages = {1150--1167},
	booktitle = {Proceedings of the 31st International Conference on Computational Linguistics},
	publisher = {Association for Computational Linguistics},
	author = {Wang, Qianli and Anikina, Tatiana and Feldhus, Nils and Ostermann, Simon and Möller, Sebastian and Schmitt, Vera},
	urldate = {2025-05-22},
	date = {2025-04},
	note = {cross-refine.jpg},
	keywords = {Coling},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/534G7A97/Wang et al. - 2025 - Cross-Refine Improving Natural Language Explanati.pdf:application/pdf},
}

@inproceedings{mikaberidze_comparison_2024,
	location = {Trento},
	title = {A Comparison of Different Tokenization Methods for the Georgian Language},
	url = {https://aclanthology.org/2024.icnlsp-1.22/},
	eventtitle = {{ICNLSP} 2024},
	pages = {199--208},
	booktitle = {Proceedings of the 7th International Conference on Natural Language and Speech Processing ({ICNLSP} 2024)},
	publisher = {Association for Computational Linguistics},
	author = {Mikaberidze, Beso and Saghinadze, Temo and Mikaberidze, Guram and Kalandadze, Raphael and Pkhakadze, Konstantine and van Genabith, Josef and Ostermann, Simon and van der Plas, Lonneke and Müller, Philipp},
	urldate = {2025-05-22},
	date = {2024-10},
	keywords = {{ICNLSP}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/C8WMZELP/Mikaberidze et al. - 2024 - A Comparison of Different Tokenization Methods for.pdf:application/pdf},
}

@inproceedings{oguz_mmar_2024,
	location = {Miami, Florida, {USA}},
	title = {{MMAR}: Multilingual and Multimodal Anaphora Resolution in Instructional Videos},
	url = {https://aclanthology.org/2024.findings-emnlp.88/},
	doi = {10.18653/v1/2024.findings-emnlp.88},
	shorttitle = {{MMAR}},
	abstract = {Multilingual anaphora resolution identifies referring expressions and implicit arguments in texts and links to antecedents that cover several languages. In the most challenging setting, cross-lingual anaphora resolution, training data, and test data are in different languages. As knowledge needs to be transferred across languages, this task is challenging, both in the multilingual and cross-lingual setting. We hypothesize that one way to alleviate some of the difficulty of the task is to include multimodal information in the form of images (i.e. frames extracted from instructional videos). Such visual inputs are by nature language agnostic, therefore cross- and multilingual anaphora resolution should benefit from visual information. In this paper, we provide the first multilingual and multimodal dataset annotated with anaphoric relations and present experimental results for end-to-end multimodal and multilingual anaphora resolution. Given gold mentions, multimodal features improve anaphora resolution results by {\textbackslash}textasciitilde10 \% for unseen languages.},
	eventtitle = {Findings 2024},
	pages = {1618--1633},
	booktitle = {Findings of the Association for Computational Linguistics: {EMNLP} 2024},
	publisher = {Association for Computational Linguistics},
	author = {Oguz, Cennet and Denis, Pascal and Ostermann, Simon and Vincent, Emmanuel and Skachkova, Natalia and Genabith, Josef Van},
	urldate = {2025-05-22},
	date = {2024-11},
	note = {mmar.jpg},
	keywords = {{EMNLP}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/LDEL8BGI/Oguz et al. - 2024 - MMAR Multilingual and Multimodal Anaphora Resolut.pdf:application/pdf},
}

@inproceedings{anikina_reverse_2025,
	location = {Albuquerque, {NM}},
	title = {Reverse Probing: Evaluating Knowledge Transfer via Finetuned Task Embeddings for Coreference Resolution},
	isbn = {9798891762459},
	url = {https://aclanthology.org/2025.repl4nlp-1.9/},
	shorttitle = {Reverse Probing},
	abstract = {In this work, we reimagine classical probing to evaluate knowledge transfer from simple source to more complex target tasks. Instead of probing frozen representations from a complex source task on diverse simple target probing tasks (as usually done in probing), we explore the effectiveness of embeddings from multiple simple source tasks on a single target task. We select coreference resolution, a linguistically complex problem requiring contextual understanding, as focus target task, and test the usefulness of embeddings from comparably simpler tasks tasks such as paraphrase detection, named entity recognition, and relation extraction. Through systematic experiments, we evaluate the impact of individual and combined task embeddings. Our findings reveal that task embeddings vary significantly in utility for coreference resolution, with semantic similarity tasks (e.g., paraphrase detection) proving most beneficial. Additionally, representations from intermediate layers of fine-tuned models often outperform those from final layers. Combining embeddings from multiple tasks consistently improves performance, with attention-based aggregation yielding substantial gains. These insights shed light on relationships between task-specific representations and their adaptability to complex downstream tasks, encouraging further exploration of embedding-level task transfer. Our source code is publicly available under https://github.com/Cora4NLP/multi-task-knowledge-transfer.},
	pages = {108--119},
	booktitle = {Proceedings of the 10th Workshop on Representation Learning for {NLP} ({RepL}4NLP-2025)},
	publisher = {Association for Computational Linguistics},
	author = {Anikina, Tatiana and Binder, Arne and Harbecke, David and Varanasi, Stalin and Hennig, Leonhard and Ostermann, Simon and Möller, Sebastian and Genabith, Josef Van},
	urldate = {2025-05-22},
	date = {2025-05},
	note = {reverseprobing.jpg},
	keywords = {Rep4NLP},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/DZDEHSHP/Anikina et al. - 2025 - Reverse Probing Evaluating Knowledge Transfer via.pdf:application/pdf},
}

@inproceedings{gurgurov_gremlin_2025,
	location = {Albuquerque, New Mexico},
	title = {{GrEmLIn}: A Repository of Green Baseline Embeddings for 87 Low-Resource Languages Injected with Multilingual Graph Knowledge},
	isbn = {9798891761957},
	url = {https://aclanthology.org/2025.findings-naacl.67/},
	shorttitle = {{GrEmLIn}},
	eventtitle = {Findings 2025},
	pages = {1204--1221},
	booktitle = {Findings of the Association for Computational Linguistics: {NAACL} 2025},
	publisher = {Association for Computational Linguistics},
	author = {Gurgurov, Daniil and Kumar, Rishu and Ostermann, Simon},
	urldate = {2025-05-22},
	date = {2025-04},
	note = {gremlin.jpg},
	keywords = {{NAACL}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/6GQ2UKAC/Gurgurov et al. - 2025 - GrEmLIn A Repository of Green Baseline Embeddings.pdf:application/pdf},
}

@thesis{ostermann_script_2020,
	title = {Script Knowledge for Natural Language Understanding},
	url = {https://publikationen.sulb.uni-saarland.de/handle/20.500.11880/29334},
	abstract = {While people process text, they make frequent use of information that is assumed to be common ground and left implicit in the text. One important type of such commonsense knowledge is script knowledge, which is the knowledge about the events and participants in everyday activities such as visiting a restaurant. Due to its implicitness, it is hard for machines to exploit such script knowledge for natural language processing ({NLP}). This dissertation addresses the role of script knowledge in a central field of {NLP}, natural language understanding ({NLU}).  In the first part of this thesis, we address script parsing. The idea of script parsing is to align event and participant mentions in a text with an underlying script representation. This makes it possible for a system to leverage script knowledge for downstream tasks. We develop the first script parsing model for events that can be trained on a large scale on crowdsourced script data. The model is implemented as a linear-chain conditional random field and trained on sequences of short event descriptions, implicitly exploiting the inherent event ordering information. We show that this ordering information plays a crucial role for script parsing. Our model provides an important first step towards facilitating the use of script knowledge for {NLU}.  In the second part of the thesis, we move our focus to an actual application in the area of {NLU}, i.e. machine comprehension. For the first time, we provide data sets for the systematic evaluation of the contribution of script knowledge for machine comprehension. We create {MCScript}, a corpus of narrations about everyday activities and questions on the texts. By collecting questions based on a scenario rather than a text, we aimed at creating challenging questions which require script knowledge for finding the correct answer. Based on the findings of a shared task carried out with the data set, which indicated that script knowledge is not relevant for good performance on our corpus, we revised the data collection process and created a second version of the data set.},
	institution = {Saarländische Universitäts- und Landesbibliothek},
	type = {{doctoralThesis}},
	author = {Ostermann, Simon},
	urldate = {2025-06-02},
	date = {2020},
	langid = {english},
	doi = {10.22028/D291-31301},
	note = {Accepted: 2020-06-29T07:21:28Z},
	keywords = {Thesis},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/4NPQLVG3/Ostermann - 2020 - Script Knowledge for Natural Language Understandin.pdf:application/pdf},
}

@inproceedings{ostermann_commonsense_2019,
	location = {Hong Kong, China},
	title = {Commonsense Inference in Natural Language Processing ({COIN}) - Shared Task Report},
	url = {https://aclanthology.org/D19-6007/},
	doi = {10.18653/v1/D19-6007},
	abstract = {This paper reports on the results of the shared tasks of the {COIN} workshop at {EMNLP}-{IJCNLP} 2019. The tasks consisted of two machine comprehension evaluations, each of which tested a system's ability to answer questions/queries about a text. Both evaluations were designed such that systems need to exploit commonsense knowledge, for example, in the form of inferences over information that is available in the common ground but not necessarily mentioned in the text. A total of five participating teams submitted systems for the shared tasks, with the best submitted system achieving 90.6\% accuracy and 83.7\% F1-score on task 1 and task 2, respectively.},
	pages = {66--74},
	booktitle = {Proceedings of the First Workshop on Commonsense Inference in Natural Language Processing},
	publisher = {Association for Computational Linguistics},
	author = {Ostermann, Simon and Zhang, Sheng and Roth, Michael and Clark, Peter},
	urldate = {2025-06-02},
	date = {2019-11},
	keywords = {{COIN}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/6QZPPI3Y/Ostermann et al. - 2019 - Commonsense Inference in Natural Language Processi.pdf:application/pdf},
}

@inproceedings{ostermann_mcscript20_2019,
	location = {Minneapolis, Minnesota},
	title = {{MCScript}2.0: A Machine Comprehension Corpus Focused on Script Events and Participants},
	url = {https://aclanthology.org/S19-1012/},
	doi = {10.18653/v1/S19-1012},
	shorttitle = {{MCScript}2.0},
	abstract = {We introduce {MCScript}2.0, a machine comprehension corpus for the end-to-end evaluation of script knowledge. {MCScript}2.0 contains approx. 20,000 questions on approx. 3,500 texts, crowdsourced based on a new collection process that results in challenging questions. Half of the questions cannot be answered from the reading texts, but require the use of commonsense and, in particular, script knowledge. We give a thorough analysis of our corpus and show that while the task is not challenging to humans, existing machine comprehension models fail to perform well on the data, even if they make use of a commonsense knowledge base. The dataset is available at http://www.sfb1102.uni-saarland.de/?page\_id=2582},
	eventtitle = {*{SEM} 2019},
	pages = {103--117},
	booktitle = {Proceedings of the Eighth Joint Conference on Lexical and Computational Semantics (*{SEM} 2019)},
	publisher = {Association for Computational Linguistics},
	author = {Ostermann, Simon and Roth, Michael and Pinkal, Manfred},
	urldate = {2025-06-02},
	date = {2019-06},
	note = {mcscript2.jpg},
	keywords = {*{SEM}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/XPL3DYLS/Ostermann et al. - 2019 - MCScript2.0 A Machine Comprehension Corpus Focuse.pdf:application/pdf},
}

@inproceedings{ostermann_semeval-2018_2018,
	location = {New Orleans, Louisiana},
	title = {{SemEval}-2018 Task 11: Machine Comprehension Using Commonsense Knowledge},
	url = {https://aclanthology.org/S18-1119/},
	doi = {10.18653/v1/S18-1119},
	shorttitle = {{SemEval}-2018 Task 11},
	abstract = {This report summarizes the results of the {SemEval} 2018 task on machine comprehension using commonsense knowledge. For this machine comprehension task, we created a new corpus, {MCScript}. It contains a high number of questions that require commonsense knowledge for finding the correct answer. 11 teams from 4 different countries participated in this shared task, most of them used neural approaches. The best performing system achieves an accuracy of 83.95\%, outperforming the baselines by a large margin, but still far from the human upper bound, which was found to be at 98\%.},
	eventtitle = {{SemEval} 2018},
	pages = {747--757},
	booktitle = {Proceedings of the 12th International Workshop on Semantic Evaluation},
	publisher = {Association for Computational Linguistics},
	author = {Ostermann, Simon and Roth, Michael and Modi, Ashutosh and Thater, Stefan and Pinkal, Manfred},
	urldate = {2025-06-02},
	date = {2018-06},
	keywords = {{SemEval}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/LDRMN4T7/Ostermann et al. - 2018 - SemEval-2018 Task 11 Machine Comprehension Using .pdf:application/pdf},
}

@inproceedings{ostermann_mcscript_2018,
	location = {Miyazaki, Japan},
	title = {{MCScript}: A Novel Dataset for Assessing Machine Comprehension Using Script Knowledge},
	url = {https://aclanthology.org/L18-1564/},
	shorttitle = {{MCScript}},
	eventtitle = {{LREC} 2018},
	booktitle = {Proceedings of the Eleventh International Conference on Language Resources and Evaluation ({LREC} 2018)},
	publisher = {European Language Resources Association ({ELRA})},
	author = {Ostermann, Simon and Modi, Ashutosh and Roth, Michael and Thater, Stefan and Pinkal, Manfred},
	urldate = {2025-06-02},
	date = {2018-05},
	note = {mcscript.jpg},
	keywords = {{LREC}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/SZDITZCC/Ostermann et al. - 2018 - MCScript A Novel Dataset for Assessing Machine Co.pdf:application/pdf},
}

@inproceedings{ostermann_mapping_2018,
	location = {Miyazaki, Japan},
	title = {Mapping Texts to Scripts: An Entailment Study},
	url = {https://aclanthology.org/L18-1512/},
	shorttitle = {Mapping Texts to Scripts},
	eventtitle = {{LREC} 2018},
	booktitle = {Proceedings of the Eleventh International Conference on Language Resources and Evaluation ({LREC} 2018)},
	publisher = {European Language Resources Association ({ELRA})},
	author = {Ostermann, Simon and Seitz, Hannah and Thater, Stefan and Pinkal, Manfred},
	urldate = {2025-06-02},
	date = {2018-05},
	keywords = {{LREC}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/LPPXJERI/Ostermann et al. - 2018 - Mapping Texts to Scripts An Entailment Study.pdf:application/pdf},
}

@inproceedings{ostermann_aligning_2017,
	location = {Vancouver, Canada},
	title = {Aligning Script Events with Narrative Texts},
	url = {https://aclanthology.org/S17-1016/},
	doi = {10.18653/v1/S17-1016},
	abstract = {Script knowledge plays a central role in text understanding and is relevant for a variety of downstream tasks. In this paper, we consider two recent datasets which provide a rich and general representation of script events in terms of paraphrase sets. We introduce the task of mapping event mentions in narrative texts to such script event types, and present a model for this task that exploits rich linguistic representations as well as information on temporal ordering. The results of our experiments demonstrate that this complex task is indeed feasible.},
	eventtitle = {*{SEM} 2017},
	pages = {128--134},
	booktitle = {Proceedings of the 6th Joint Conference on Lexical and Computational Semantics (*{SEM} 2017)},
	publisher = {Association for Computational Linguistics},
	author = {Ostermann, Simon and Roth, Michael and Thater, Stefan and Pinkal, Manfred},
	urldate = {2025-06-02},
	date = {2017-08},
	note = {aligning\_scripts.jpg},
	keywords = {*{SEM}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/AJCTSIIH/Ostermann et al. - 2017 - Aligning Script Events with Narrative Texts.pdf:application/pdf},
}

@inproceedings{modi_inscript_2016,
	location = {Portorož, Slovenia},
	title = {{InScript}: Narrative texts annotated with script information},
	url = {https://aclanthology.org/L16-1555/},
	shorttitle = {{InScript}},
	abstract = {This paper presents the {InScript} corpus (Narrative Texts Instantiating Script structure). {InScript} is a corpus of 1,000 stories centered around 10 different scenarios. Verbs and noun phrases are annotated with event and participant types, respectively. Additionally, the text is annotated with coreference information. The corpus shows rich lexical variation and will serve as a unique resource for the study of the role of script knowledge in natural language processing.},
	eventtitle = {{LREC} 2016},
	pages = {3485--3493},
	booktitle = {Proceedings of the Tenth International Conference on Language Resources and Evaluation ({LREC}'16)},
	publisher = {European Language Resources Association ({ELRA})},
	author = {Modi, Ashutosh and Anikina, Tatjana and Ostermann, Simon and Pinkal, Manfred},
	urldate = {2025-06-02},
	date = {2016-05},
	keywords = {{LREC}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/VZ66Y6YA/Modi et al. - 2016 - InScript Narrative texts annotated with script in.pdf:application/pdf},
}

@inproceedings{ostermann_annotating_2015,
	location = {Beijing, China},
	title = {Annotating Entailment Relations for Shortanswer Questions},
	url = {https://aclanthology.org/W15-4408/},
	doi = {10.18653/v1/W15-4408},
	eventtitle = {{NLP}-{TEA} 2015},
	pages = {49--58},
	booktitle = {Proceedings of the 2nd Workshop on Natural Language Processing Techniques for Educational Applications},
	publisher = {Association for Computational Linguistics},
	author = {Ostermann, Simon and Horbach, Andrea and Pinkal, Manfred},
	urldate = {2025-06-02},
	date = {2015-07},
	keywords = {{NLP}-{TEA}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/WSLYEVRW/Ostermann et al. - 2015 - Annotating Entailment Relations for Shortanswer Qu.pdf:application/pdf},
}

@inproceedings{koleva_paraphrase_2014,
	location = {Uppsala, Sweden},
	title = {Paraphrase Detection for Short Answer Scoring},
	url = {https://aclanthology.org/W14-3505/},
	eventtitle = {{NLP}4CALL 2014},
	pages = {59--73},
	booktitle = {Proceedings of the third workshop on {NLP} for computer-assisted language learning},
	publisher = {{LiU} Electronic Press},
	author = {Koleva, Nikolina and Horbach, Andrea and Palmer, Alexis and Ostermann, Simon and Pinkal, Manfred},
	urldate = {2025-06-02},
	date = {2014-11},
	keywords = {{NLP}4CALL},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/NAHJXY9H/Koleva et al. - 2014 - Paraphrase Detection for Short Answer Scoring.pdf:application/pdf},
}

@inproceedings{belanec_task_2025,
	title = {Task Prompt Vectors: Effective Initialization through Multi-Task Soft-Prompt Transfer},
	url = {http://arxiv.org/abs/2408.01119},
	doi = {10.48550/arXiv.2408.01119},
	shorttitle = {Task Prompt Vectors},
	abstract = {Prompt tuning is an efficient solution for training large language models ({LLMs}). However, current soft-prompt-based methods often sacrifice multi-task modularity, requiring the training process to be fully or partially repeated for each newly added task. While recent work on task vectors applied arithmetic operations on full model weights to achieve the desired multi-task performance, a similar approach for soft-prompts is still missing. To this end, we introduce Task Prompt Vectors, created by element-wise difference between weights of tuned soft-prompts and their random initialization. Experimental results on 12 {NLU} datasets show that task prompt vectors can be used in low-resource settings to effectively initialize prompt tuning on similar tasks. In addition, we show that task prompt vectors are independent of the random initialization of prompt tuning on 2 different language model architectures. This allows prompt arithmetics with the pre-trained vectors from different tasks. In this way, we provide a competitive alternative to state-of-the-art baselines by arithmetic addition of task prompt vectors from multiple tasks.},
	eventtitle = {European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases ({ECML}-{PKDD}).},
	booktitle = {Accepted at European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases ({ECML}-{PKDD}).},
	author = {Belanec, Robert and Ostermann, Simon and Srba, Ivan and Bielikova, Maria},
	urldate = {2025-06-02},
	date = {2025-07},
	note = {vectors.jpg},
	keywords = {{ECML}},
	file = {Preprint PDF:/Users/sios01-admin/Zotero/storage/FVMWMI7B/Belanec et al. - 2024 - Task Prompt Vectors Effective Initialization thro.pdf:application/pdf;Snapshot:/Users/sios01-admin/Zotero/storage/RRYXYI8X/2408.html:text/html},
}

@inproceedings{peng_semeval-2025_2025,
	location = {Vienna, Austria},
	title = {{SemEval}-2025 Task 7: Multilingual and Crosslingual Fact-Checked Claim Retrieval},
	isbn = {9798891762732},
	url = {https://aclanthology.org/2025.semeval-1.323/},
	shorttitle = {{SemEval}-2025 Task 7},
	abstract = {The rapid spread of online disinformation presents a global challenge, and machine learning has been widely explored as a potential solution. However, multilingual settings and low-resource languages are often neglected in this field. To address this gap, we conducted a shared task on multilingual claim retrieval at {SemEval} 2025, aimed at identifying fact-checked claims that match newly encountered claims expressed in social media posts across different languages. The task includes two subtracks: 1) a monolingual track, where social posts and claims are in the same language 2) a crosslingual track, where social posts and claims might be in different languages. A total of 179 participants registered for the task contributing to 52 test submissions. 23 out of 31 teams have submitted their system papers. In this paper, we report the best-performing systems as well as the most common and the most effective approaches across both subtracks. This shared task, along with its dataset and participating systems, provides valuable insights into multilingual claim retrieval and automated fact-checking, supporting future research in this field.},
	eventtitle = {{SemEval} 2025},
	pages = {2498--2511},
	booktitle = {Proceedings of the 19th International Workshop on Semantic Evaluation ({SemEval}-2025)},
	publisher = {Association for Computational Linguistics},
	author = {Peng, Qiwei and Moro, Robert and Gregor, Michal and Srba, Ivan and Ostermann, Simon and Simko, Marian and Podrouzek, Juraj and Mesarčík, Matúš and Kopčan, Jaroslav and Søgaard, Anders},
	editor = {Rosenthal, Sara and Rosá, Aiala and Ghosh, Debanjan and Zampieri, Marcos},
	urldate = {2025-08-11},
	date = {2025-07},
	note = {semeval25.jpg},
	keywords = {{SemEval}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/ZL5W8L8I/Peng et al. - 2025 - SemEval-2025 Task 7 Multilingual and Crosslingual.pdf:application/pdf},
}

@inproceedings{vykopal_large_2025,
	title = {Large Language Models for Multilingual Previously Fact-Checked Claim Detection},
	rights = {facts.jpg},
	url = {http://arxiv.org/abs/2503.02737},
	doi = {10.48550/arXiv.2503.02737},
	abstract = {In our era of widespread false information, human fact-checkers often face the challenge of duplicating efforts when verifying claims that may have already been addressed in other countries or languages. As false information transcends linguistic boundaries, the ability to automatically detect previously fact-checked claims across languages has become an increasingly important task. This paper presents the first comprehensive evaluation of large language models ({LLMs}) for multilingual previously fact-checked claim detection. We assess seven {LLMs} across 20 languages in both monolingual and cross-lingual settings. Our results show that while {LLMs} perform well for high-resource languages, they struggle with low-resource languages. Moreover, translating original texts into English proved to be beneficial for low-resource languages. These findings highlight the potential of {LLMs} for multilingual previously fact-checked claim detection and provide a foundation for further research on this promising application of {LLMs}.},
	booktitle = {Accepted for Findings of {EMNLP} 2025},
	publisher = {{arXiv}},
	author = {Vykopal, Ivan and Pikuliak, Matúš and Ostermann, Simon and Anikina, Tatiana and Gregor, Michal and Šimko, Marián},
	urldate = {2025-08-21},
	date = {2025-10},
	eprinttype = {arxiv},
	eprint = {2503.02737 [cs]},
	keywords = {{EMNLP}},
	file = {Preprint PDF:/Users/sios01-admin/Zotero/storage/ZN8WTF7L/Vykopal et al. - 2025 - Large Language Models for Multilingual Previously .pdf:application/pdf;Snapshot:/Users/sios01-admin/Zotero/storage/56V2AF69/2503.html:text/html},
}

@inproceedings{anikina_rigorous_2025,
	title = {A Rigorous Evaluation of {LLM} Data Generation Strategies for Low-Resource Languages},
	url = {http://arxiv.org/abs/2506.12158},
	doi = {10.48550/arXiv.2506.12158},
	abstract = {Large Language Models ({LLMs}) are increasingly used to generate synthetic textual data for training smaller specialized models. However, a comparison of various generation strategies for low-resource language settings is lacking. While various prompting strategies have been proposed, such as demonstrations, label-based summaries, and self-revision, their comparative effectiveness remains unclear, especially for low-resource languages. In this paper, we systematically evaluate the performance of these generation strategies and their combinations across 11 typologically diverse languages, including several extremely low-resource ones. Using three {NLP} tasks and four open-source {LLMs}, we assess downstream model performance on generated versus gold-standard data. Our results show that strategic combinations of generation methods, particularly target-language demonstrations with {LLM}-based revisions, yield strong performance, narrowing the gap with real data to as little as 5\% in some settings. We also find that smart prompting techniques can reduce the advantage of larger {LLMs}, highlighting efficient generation strategies for synthetic data generation in low-resource scenarios with smaller models.},
	booktitle = {Accepted for {EMNLP} 2025 (Main Conference)},
	publisher = {{arXiv}},
	author = {Anikina, Tatiana and Cegin, Jan and Simko, Jakub and Ostermann, Simon},
	urldate = {2025-08-21},
	date = {2025-10-01},
	note = {synthetic.jpg},
	keywords = {{EMNLP}},
	annotation = {Comment: 21 pages, fixed typo},
	file = {Preprint PDF:/Users/sios01-admin/Zotero/storage/8KM5YHMJ/Anikina et al. - 2025 - A Rigorous Evaluation of LLM Data Generation Strat.pdf:application/pdf;Snapshot:/Users/sios01-admin/Zotero/storage/R2D8ACE5/2506.html:text/html},
}

@inproceedings{wang_fitcf_2025,
	location = {Vienna, Austria},
	title = {{FitCF}: A Framework for Automatic Feature Importance-guided Counterfactual Example Generation},
	isbn = {9798891762565},
	url = {https://aclanthology.org/2025.findings-acl.64/},
	doi = {10.18653/v1/2025.findings-acl.64},
	shorttitle = {{FitCF}},
	abstract = {Counterfactual examples are widely used in natural language processing ({NLP}) as valuable data to improve models, and in explainable artificial intelligence ({XAI}) to understand model behavior. The automated generation of counterfactual examples remains a challenging task even for large language models ({LLMs}), despite their impressive performance on many tasks. In this paper, we first introduce {ZeroCF}, a faithful approach for leveraging important words derived from feature attribution methods to generate counterfactual examples in a zero-shot setting. Second, we present a new framework, {FitCF}, which further verifies aforementioned counterfactuals by label flip verification and then inserts them as demonstrations for few-shot prompting, outperforming three state-of-the-art baselines. Through ablation studies, we identify the importance of each of {FitCF}'s core components in improving the quality of counterfactuals, as assessed through flip rate, perplexity, and similarity measures. Furthermore, we show the effectiveness of {LIME} and Integrated Gradients as backbone attribution methods for {FitCF} and find that the number of demonstrations has the largest effect on performance. Finally, we reveal a strong correlation between the faithfulness of feature attribution scores and the quality of generated counterfactuals, which we hope will serve as an importantfinding for future research in this direction.},
	eventtitle = {Findings 2025},
	pages = {1176--1191},
	booktitle = {Findings of the Association for Computational Linguistics: {ACL} 2025},
	publisher = {Association for Computational Linguistics},
	author = {Wang, Qianli and Feldhus, Nils and Ostermann, Simon and Villa-Arenas, Luis Felipe and Möller, Sebastian and Schmitt, Vera},
	editor = {Che, Wanxiang and Nabende, Joyce and Shutova, Ekaterina and Pilehvar, Mohammad Taher},
	urldate = {2025-08-21},
	date = {2025-07},
	note = {fitcf.jpg},
	keywords = {{ACL}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/5HQF2MJZ/Wang et al. - 2025 - FitCF A Framework for Automatic Feature Importanc.pdf:application/pdf},
}

@inproceedings{wang_multilingual_2025,
	title = {Multilingual Datasets for Custom Input Extraction and Explanation Requests Parsing in Conversational {XAI} Systems},
	abstract = {Conversational explainable artificial intelligence ({ConvXAI}) systems based on large language models ({LLMs}) have garnered considerable attention for their ability to enhance user comprehension through dialogue-based explanations. Current {ConvXAI} systems are often based on intent recognition to accurately identify the user’s desired intention and map it to an explainability method. While such methods offer great precision and reliability in discerning users’ underlying intentions for English, a significant challenge in the scarcity of training data persists, which impedes multilingual generalization. Besides, the support for free-form custom inputs, which are user-defined data distinct from pre-configured dataset instances, remains largely limited. To bridge these gaps, we first introduce {MultiCoXQL}, a multilingual extension of the {CoXQL} dataset spanning five typologically diverse languages, including one low-resource language. Subsequently, we propose a new parsing approach aimed at enhancing multilingual parsing performance, and evaluate three {LLMs} on {MultiCoXQL} using various parsing strategies. Furthermore, we present Compass, a new multilingual dataset designed for custom input extraction in {ConvXAI} systems, encompassing 11 intents across the same five languages as {MultiCoXQL}1. We conduct monolingual, cross-lingual, and multilingual evaluations on Compass, employing three {LLMs} of varying sizes alongside {BERT}-type models.},
	booktitle = {Accepted for Findings of {EMNLP} 2025},
	author = {Wang, Qianli and Anikina, Tatiana and Feldhus, Nils and Ostermann, Simon and Splitt, Fedor and Li, Jiaao and Tsoneva, Yoana and Möller, Sebastian and Schmitt, Vera},
	date = {2025-10},
	langid = {english},
	keywords = {{EMNLP}},
	file = {Wang et al. - Multilingual Datasets for Custom Input Extraction .pdf:/Users/sios01-admin/Zotero/storage/W96BGNDT/Wang et al. - Multilingual Datasets for Custom Input Extraction .pdf:application/pdf},
}

@inproceedings{schlenker_only_2025,
	location = {Vienna, Austria},
	title = {Only for the Unseen Languages, Say the Llamas: On the Efficacy of Language Adapters for Cross-lingual Transfer in English-centric {LLMs}},
	isbn = {9798891762541},
	url = {https://aclanthology.org/2025.acl-srw.62/},
	doi = {10.18653/v1/2025.acl-srw.62},
	shorttitle = {Only for the Unseen Languages, Say the Llamas},
	abstract = {Most state-of-the-art large language models ({LLMs}) are trained mainly on English data, limiting their effectiveness on non-English, especially low-resource, languages. This study investigates whether language adapters can facilitate cross-lingual transfer in English-centric {LLMs}. We train language adapters for 13 languages using Llama 2 (7B) and Llama 3.1 (8B) as base models, and evaluate their effectiveness on two downstream tasks ({MLQA} and {SIB}-200) using either task adapters or in-context learning. Our results reveal that language adapters improve performance for languages not seen during pretraining, but provide negligible benefit for seen languages. These findings highlight the limitations of language adapters as a general solution for multilingual adaptation in English-centric {LLMs}.},
	pages = {849--871},
	booktitle = {Proceedings of the 63rd Annual Meeting of the Association for Computational Linguistics (Volume 4: Student Research Workshop)},
	publisher = {Association for Computational Linguistics},
	author = {Schlenker, Julian and Kunz, Jenny and Anikina, Tatiana and Neumann, Günter and Ostermann, Simon},
	editor = {Zhao, Jin and Wang, Mingyang and Liu, Zhu},
	urldate = {2025-08-22},
	date = {2025-07},
	keywords = {{ACL}-{SRW}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/HCPFTIUL/Schlenker et al. - 2025 - Only for the Unseen Languages, Say the Llamas On .pdf:application/pdf},
}

@inproceedings{gurgurov_small_2025,
	location = {Vienna, Austria},
	title = {Small Models, Big Impact: Efficient Corpus and Graph-Based Adaptation of Small Multilingual Language Models for Low-Resource Languages},
	isbn = {9798891762541},
	url = {https://aclanthology.org/2025.acl-srw.24/},
	doi = {10.18653/v1/2025.acl-srw.24},
	shorttitle = {Small Models, Big Impact},
	abstract = {Low-resource languages ({LRLs}) face significant challenges in natural language processing ({NLP}) due to limited data. While current state-of-the-art large language models ({LLMs}) still struggle with {LRLs}, smaller multilingual models ({mLMs}) such as {mBERT} and {XLM}-R offer greater promise due to a better fit of their capacity to low training data sizes. This study systematically investigates parameter-efficient adapter-based methods for adapting {mLMs} to {LRLs}, evaluating three architectures: Sequential Bottleneck, Invertible Bottleneck, and Low-Rank Adaptation. Using unstructured text from {GlotCC} and structured knowledge from {ConceptNet}, we show that small adaptation datasets (e.g., up to 1 {GB} of free-text or a few {MB} of knowledge graph data) yield gains in intrinsic (masked language modeling) and extrinsic tasks (topic classification, sentiment analysis, and named entity recognition). We find that Sequential Bottleneck adapters excel in language modeling, while Invertible Bottleneck adapters slightly outperform other methods on downstream tasks due to better embedding alignment and larger parameter counts. Adapter-based methods match or outperform full fine-tuning while using far fewer parameters, and smaller {mLMs} prove more effective for {LRLs} than massive {LLMs} like {LLaMA}-3, {GPT}-4, and {DeepSeek}-R1-based distilled models. While adaptation improves performance, pre-training data size remains the dominant factor, especially for languages with extensive pre-training coverage.The code for our experiments is available at https://github.com/d-gurgurov/Knowledge-Driven-Adaptation-{LLMs}.},
	pages = {355--395},
	booktitle = {Proceedings of the 63rd Annual Meeting of the Association for Computational Linguistics (Volume 4: Student Research Workshop)},
	publisher = {Association for Computational Linguistics},
	author = {Gurgurov, Daniil and Vykopal, Ivan and Genabith, Josef Van and Ostermann, Simon},
	editor = {Zhao, Jin and Wang, Mingyang and Liu, Zhu},
	urldate = {2025-08-22},
	date = {2025-07},
	keywords = {{ACL}-{SRW}},
	file = {Full Text PDF:/Users/sios01-admin/Zotero/storage/KEGDN9W6/Gurgurov et al. - 2025 - Small Models, Big Impact Efficient Corpus and Gra.pdf:application/pdf},
}

@inproceedings{baeumel_lookahead_2025,
	title = {The Lookahead Limitation: Why Multi-Operand Addition is Hard for {LLMs}},
	url = {http://arxiv.org/abs/2502.19981},
	doi = {10.48550/arXiv.2502.19981},
	shorttitle = {The Lookahead Limitation},
	abstract = {Autoregressive large language models ({LLMs}) exhibit impressive performance across various tasks but struggle with simple arithmetic, such as addition of two or more operands. We show that this struggle arises from {LLMs}' use of a simple one-digit lookahead heuristic, which works fairly well (but not perfect) for two-operand addition but fails in multi-operand cases, where the carry-over logic is more complex. Our probing experiments and digit-wise accuracy evaluation show that {LLMs} fail precisely where a one-digit lookahead is insufficient to account for cascading carries. We analyze the impact of tokenization strategies on arithmetic performance and show that all investigated models, regardless of tokenization, are inherently limited in the addition of multiple operands due to their reliance on a one-digit lookahead heuristic. Our findings reveal fundamental limitations that prevent {LLMs} from generalizing to more complex numerical reasoning.},
	booktitle = {Accepted at the 6th {BlackboxNLP} Workshop: Analyzing and Interpreting Neural Networks for {NLP}},
	author = {Baeumel, Tanja and Genabith, Josef van and Ostermann, Simon},
	urldate = {2025-08-22},
	date = {2025-11},
	note = {lookahead.jpg},
	keywords = {{BlackBoxNLP}},
	annotation = {Comment: Pre-print},
	file = {Preprint PDF:/Users/sios01-admin/Zotero/storage/SM873RWL/Baeumel et al. - 2025 - The Lookahead Limitation Why Multi-Operand Additi.pdf:application/pdf;Snapshot:/Users/sios01-admin/Zotero/storage/2PMG25I8/2502.html:text/html},
}
`;
